CREATE TABLE IF NOT EXISTS `stocks` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`arg` VARCHAR(50) NULL DEFAULT NULL,
	`sector` VARCHAR(50) NULL DEFAULT NULL,
	`code` VARCHAR(50) NOT NULL,
	`pe_ratio` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `code` (`code`) USING BTREE
);
